export const Listado_Alumnos = [
{
    id: 1,
    nombre: "bAutista",
    apellido: "Figueroa",
    dni: 49000000,
    curso: "Primero B",
    email: "bAgueroa@gmail.com",
    telefono: 123456789,
    domiciolio: "Calle Falsa 123",
    visible: true,
  },
  {
    id: 2,
    nombre: "Lautaro",
    apellido: "Fernandez",
    dni: 43434320,
    curso: "Tercero A",
    email: "LauFer@gmail.com",
    telefono: 987654321,
    domiciolio: "Calle Verdadera 456",
    visible: true,
  },
  {
    id: 3,
    nombre: "Maria",
    apellido: "Martinez",
    dni: 47029034,
    curso: "Primero B",
    email: "MarMar@gmail.com",
    telefono: 456789123,
    domiciolio: "Calle Real 789",
    visible: true,
  },

]